# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('product', '0002_auto_20170616_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier.Supplier', verbose_name='product supplier'),
        ),
    ]
