# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_product_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last history change')),
                ('comment', models.CharField(blank=True, default='', max_length=100, verbose_name='comment')),
                ('crud', models.CharField(blank=True, default='', max_length=30, verbose_name='crud')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='product.Stock', verbose_name='order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Stock history entry',
                'verbose_name_plural': 'Stock history entries',
            },
        ),
    ]
