# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-01 09:16
from __future__ import unicode_literals

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'facebook', b'Facebook-Oauth2'), (b'google-oauth2', b'Google-Oauth2')], max_length=20, verbose_name='name')),
                ('key', models.TextField(verbose_name='key')),
                ('password', models.TextField(verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('header_text', models.CharField(blank=True, max_length=200, verbose_name='header text')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='site description')),
            ],
        ),
        migrations.AddField(
            model_name='authorizationkey',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings'),
        ),
        migrations.AlterUniqueTogether(
            name='authorizationkey',
            unique_together=set([('site_settings', 'name')]),
        ),
    ]
