# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20170610_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('access_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
