# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_usertrail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrail',
            name='access_date',
        ),
        migrations.AddField(
            model_name='usertrail',
            name='crud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertrail',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 18)),
        ),
        migrations.AddField(
            model_name='usertrail',
            name='now',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
