# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20170618_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='images/user.png', upload_to='staff'),
        ),
        migrations.AlterField(
            model_name='usertrail',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 19)),
        ),
    ]
