# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20170619_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='staff/user.png', upload_to='staff'),
        ),
    ]
