# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 07:44
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('ref_number', models.CharField(max_length=100, null=True, verbose_name='terminal')),
                ('invoice_number', models.CharField(max_length=36, null=True, verbose_name='invoice_number')),
                ('transaction_type', models.CharField(max_length=36, null=True, verbose_name='transation type')),
                ('trans_id', models.CharField(max_length=36, null=True, verbose_name='trans Id')),
                ('trans_time', models.CharField(max_length=36, null=True, verbose_name='trans time')),
                ('business_shortcode', models.CharField(max_length=36, null=True, verbose_name='business shortcode')),
                ('bill_refNumber', models.CharField(max_length=36, null=True, verbose_name='bill reference number')),
                ('phone', models.CharField(max_length=36, null=True, verbose_name='phone')),
                ('first_name', models.CharField(max_length=36, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(max_length=36, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=36, null=True, verbose_name='last name')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='amount')),
            ],
            options={
                'verbose_name': 'MpesaPayment',
                'verbose_name_plural': 'MpesaPayment',
            },
        ),
    ]
