# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapayment',
            old_name='transation_type',
            new_name='transaction_type',
        ),
    ]
