# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-01 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models
import jsonfield.fields
import satchless.item
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('status', models.CharField(choices=[('open', 'Open - currently active'), ('payment', 'Waiting for payment'), ('saved', 'Saved - for items to be purchased later'), ('ordered', 'Submitted - an order was placed'), ('checkout', 'Checkout - processed in checkout'), ('canceled', 'Canceled - canceled by user')], default='open', max_length=32, verbose_name='order status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_status_change', models.DateTimeField(auto_now_add=True, verbose_name='last status change')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='token')),
                ('checkout_data', jsonfield.fields.JSONField(editable=False, null=True, verbose_name='checkout data')),
                ('total', django_prices.models.PriceField(currency='KES', decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
            ],
            options={
                'ordering': ('-last_status_change',),
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='quantity')),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='data')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.Cart', verbose_name='cart')),
            ],
            options={
                'verbose_name': 'Cart line',
                'verbose_name_plural': 'Cart lines',
            },
            bases=(models.Model, satchless.item.ItemLine),
        ),
    ]
