# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 05:09
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, verbose_name='given name')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='family name')),
                ('company_name', models.CharField(blank=True, max_length=256, verbose_name='company or organization')),
                ('street_address_1', models.CharField(blank=True, max_length=256, verbose_name='address')),
                ('street_address_2', models.CharField(blank=True, max_length=256, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=256, verbose_name='city')),
                ('city_area', models.CharField(blank=True, max_length=128, verbose_name='district')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('country_area', models.CharField(blank=True, max_length=128, verbose_name='state or province')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'address book',
                'verbose_name_plural': 'address books',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('loyalty_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='loyalty points')),
                ('nid', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined')),
                ('addresses', models.ManyToManyField(blank=True, to='customer.AddressBook', verbose_name='addresses')),
                ('default_billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.AddressBook', verbose_name='default billing address')),
                ('default_shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.AddressBook', verbose_name='default shipping address')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
    ]
