# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-01 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('fixed', 'KES'), ('percentage', '%')], default='fixed', max_length=10, verbose_name='type')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='value')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('value', 'All purchases'), ('product', 'One product'), ('category', 'A category of products'), ('shipping', 'Shipping')], default='value', max_length=20, verbose_name='discount for')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='code')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage limit')),
                ('used', models.PositiveIntegerField(default=0, editable=False)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('discount_value_type', models.CharField(choices=[('fixed', 'KES'), ('percentage', '%')], default='fixed', max_length=10, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='discount value')),
                ('apply_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='apply to')),
                ('limit', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='limit')),
            ],
            options={
                'verbose_name': 'voucher',
                'verbose_name_plural': 'vouchers',
            },
        ),
    ]
