# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product',
        ),
    ]
