# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 08:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prices.models
import saleor.search.index
import satchless.item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'new', 'Processing'), (b'cancelled', 'Cancelled'), (b'shipped', 'Shipped'), (b'payment-pending', 'Payment pending'), (b'fully-paid', 'Fully paid')], default=b'new', max_length=32, verbose_name='delivery status')),
                ('shipping_price', django_prices.models.PriceField(currency='KES', decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='shipping price')),
                ('shipping_method_name', models.CharField(blank=True, default=None, editable=False, max_length=255, null=True, verbose_name='shipping method name')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255, verbose_name='tracking number')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'Delivery Group',
                'verbose_name_plural': 'Delivery Groups',
            },
            bases=(models.Model, satchless.item.ItemSet),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'new', 'Processing'), (b'cancelled', 'Cancelled'), (b'shipped', 'Shipped'), (b'payment-pending', 'Payment pending'), (b'fully-paid', 'Fully paid')], default=b'new', max_length=32, verbose_name='order status')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('last_status_change', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last status change')),
                ('language_code', models.CharField(default='en-us', max_length=35)),
                ('tracking_client_id', models.CharField(blank=True, editable=False, max_length=36, verbose_name='tracking client id')),
                ('user_email', models.EmailField(blank=True, default='', editable=False, max_length=254, verbose_name='user email')),
                ('token', models.CharField(max_length=36, null=True, verbose_name='token')),
                ('total_net', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='total net')),
                ('total_tax', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='total tax')),
                ('discount_amount', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='discount amount')),
                ('discount_name', models.CharField(blank=True, default='', max_length=255, verbose_name='discount name')),
            ],
            options={
                'ordering': ('-last_status_change',),
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
            bases=(models.Model, satchless.item.ItemSet, saleor.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, verbose_name='product name')),
                ('product_sku', models.CharField(max_length=32, verbose_name='sku')),
                ('stock_location', models.CharField(default='', max_length=100, verbose_name='stock location')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='quantity')),
                ('unit_price_net', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='unit price (net)')),
                ('unit_price_gross', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='unit price (gross)')),
            ],
            options={
                'verbose_name': 'Ordered item',
                'verbose_name_plural': 'Ordered items',
            },
            bases=(models.Model, satchless.item.ItemLine),
        ),
        migrations.CreateModel(
            name='OrderHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last history change')),
                ('status', models.CharField(choices=[(b'new', 'Processing'), (b'cancelled', 'Cancelled'), (b'shipped', 'Shipped'), (b'payment-pending', 'Payment pending'), (b'fully-paid', 'Fully paid')], max_length=32, verbose_name='order status')),
                ('comment', models.CharField(blank=True, default='', max_length=100, verbose_name='comment')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Order history entry',
                'verbose_name_plural': 'Order history entries',
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=250, verbose_name='content')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='order.Order')),
            ],
            options={
                'verbose_name': 'Order note',
                'verbose_name_plural': 'Order notes',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(b'waiting', 'Waiting for confirmation'), (b'preauth', 'Pre-authorized'), (b'confirmed', 'Confirmed'), (b'rejected', 'Rejected'), (b'refunded', 'Refunded'), (b'error', 'Error'), (b'input', 'Input')], default=b'waiting', max_length=10)),
                ('fraud_status', models.CharField(choices=[(b'unknown', 'Unknown'), (b'accept', 'Passed'), (b'reject', 'Rejected'), (b'review', 'Review')], default=b'unknown', max_length=10, verbose_name='fraud check')),
                ('fraud_message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('delivery', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('tax', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_postcode', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=36)),
                ('captured_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.Order', verbose_name='order')),
            ],
            options={
                'ordering': ('-pk',),
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
