# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 19:48
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prices.models
import satchless.item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0011_usertrail'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('quantity', models.IntegerField(default=Decimal('1'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity')),
                ('product_name', models.CharField(max_length=128, verbose_name='product name')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'new', 'Processing'), (b'cancelled', 'Cancelled'), (b'shipped', 'Shipped'), (b'payment-pending', 'Payment pending'), (b'fully-paid', 'Fully paid')], default=b'new', max_length=32, verbose_name='order status')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('last_status_change', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last status change')),
                ('language_code', models.CharField(default='en-us', max_length=35)),
                ('user_email', models.EmailField(blank=True, default='', editable=False, max_length=254, verbose_name='user email')),
                ('terminal', models.CharField(max_length=36, null=True, verbose_name='terminal')),
                ('invoice_number', models.CharField(max_length=36, null=True, verbose_name='invoice_number')),
                ('total_net', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='total net')),
                ('sub_total', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='sub total')),
                ('total_tax', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='total tax')),
                ('amount_paid', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='amount paid')),
                ('balance', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='total tax')),
                ('discount_amount', django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='discount amount')),
                ('discount_name', models.CharField(blank=True, default='', max_length=255, verbose_name='discount name')),
                ('billing_address', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='userprofile.Address', verbose_name='billing address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='discount.Voucher', verbose_name='voucher')),
            ],
            options={
                'ordering': ('-last_status_change',),
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
            bases=(models.Model, satchless.item.ItemSet),
        ),
        migrations.AddField(
            model_name='item',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.Sales'),
        ),
    ]
