# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ('-last_status_change',), 'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[(b'new', 'Processing'), (b'cancelled', 'Cancelled'), (b'shipped', 'Shipped'), (b'payment-pending', 'Payment pending'), (b'fully-paid', 'Fully paid')], default=b'new', max_length=32, verbose_name='sales status'),
        ),
    ]
