# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20170612_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='sales',
            name='voucher',
        ),
        migrations.AddField(
            model_name='track',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='sale.Sales'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('sales', 'order')]),
        ),
    ]
