# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20170628_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='product_category',
            field=models.CharField(max_length=128, null=True, verbose_name='product_category'),
        ),
    ]
