# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 01:51
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20170612_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('quantity', models.IntegerField(default=Decimal('1'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity')),
                ('product_name', models.CharField(max_length=128, verbose_name='product name')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solditems', to='sale.Sales')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='track',
            name='sales',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AlterUniqueTogether(
            name='solditem',
            unique_together=set([('sales', 'order')]),
        ),
    ]
