# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20170612_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditem',
            name='sku',
            field=models.CharField(max_length=32, verbose_name='SKU'),
        ),
    ]
