# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20170612_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sales',
        ),
        migrations.AlterModelOptions(
            name='solditem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='solditem',
            unique_together=set([('sales',)]),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
