# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20170612_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solditem',
            unique_together=set([]),
        ),
    ]
