# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 03:37
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20170612_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='total_tax',
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(blank=True, default=Decimal('0'), null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
    ]
