# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 03:41
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20170612_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('quantity', models.IntegerField(default=Decimal('1'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity')),
                ('product_name', models.CharField(max_length=128, verbose_name='product name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='solditem',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sales',
            name='total_tax',
            field=django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='total tax'),
        ),
        migrations.AlterUniqueTogether(
            name='solditem',
            unique_together=set([('sales', 'order')]),
        ),
        migrations.AddField(
            model_name='item',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.Sales'),
        ),
    ]
