# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 03:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20170612_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='amount paid'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='sub total'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='total net'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='total tax'),
        ),
    ]
