# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_auto_20170612_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solditem',
            unique_together=set([]),
        ),
    ]
