# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20170614_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sales',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
