# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 12:42
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_solditem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='total cost'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='unit cost'),
        ),
    ]
