# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 14:16
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_auto_20170619_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='total_cost',
            field=models.IntegerField(default=Decimal('1'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='total cost'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='unit_cost',
            field=models.IntegerField(default=Decimal('1'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit cost'),
        ),
    ]
