# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sale', '0013_auto_20170619_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.Customer', verbose_name='customer'),
        ),
    ]
