# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 13:01
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sale', '0013_auto_20170620_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.Customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='total cost'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='unit cost'),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='solditem',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
